server:
  port: 8060

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mvola-service
          uri: lb://mvola-service
          predicates:
            - Path=/mvola/**
        - id: airtel-service
          uri: lb://airtel-service
          predicates:
            - Path=/airtel/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
